/* ==========================================================================
 * AXIOM — Reactive Storylines
 * "The story is not authored — it is generated by the collision between a
 * protagonist with a specific character and a world with its own momentum."
 *
 * Story BEATS fire when their conditions are met: some belong to a specific
 * protagonist's arc; many fire off HOW YOU PLAY (your style profile, your
 * underworld rank, your standing). Each beat is a choice with consequences.
 * No binary morality — every option costs something and gives something.
 * ========================================================================== */

const Story = {};
window.Story = Story;
Story._active = null;

/* shorthand for effects */
function sf(g, fac, n) { Engine.shiftFaction(g, fac, n); }
function rep(g, d, n) { g.rep[d] = Engine.clamp((g.rep[d] || 0) + n, -100, 100); }
function coin(g, n) { g.money = Math.max(0, g.money + n); }
function flag(g, k, v) { g.flags[k] = v == null ? true : v; }
function style(g, k, n) { Engine.style(g, k, n); }
function dom(g) { return Engine.dominantStyle(g); }
function S(g, k) { return (g.style && g.style[k]) || 0; }
function rank(g) { return Engine.underworldRank(g); }

/* --------------------------------------------------------------------------
 * The beats. cond(g) -> eligible. choices[].fx(g) -> applies effects, returns
 * the line written to the Record. Reference style/rank/flags so the world is
 * reacting to the specific history this player has made.
 * -------------------------------------------------------------------------- */
Story.BEATS = [

  /* ===== SHARED — fire off how you've been playing ===== */
  { id: "blooded", prio: 5,
    cond: (g) => S(g, "violence") >= 8 && g.day >= 2 && Engine.factionRep(g, "ironwall") < 60,
    title: "A Reputation for Violence",
    text: () => "You have left enough blood behind you that the Ironwall families have started saying your name. A scarred lieutenant finds you and offers steady, ugly work — the kind you've shown you're good at.",
    choices: [
      { label: "Take the family's coin — this is who you are now.", fx: (g) => { sf(g, "ironwall", 8); style(g, "violence", 2); coin(g, 40); return "You sign on as a family blade. The Ironwall opens its doors; the temple closes its."; } },
      { label: "Refuse. You are not their weapon.", fx: (g) => { sf(g, "ironwall", -4); Engine.addHeat(g, 6); return "You turn the lieutenant down. The refusal is remembered, and not kindly."; } },
    ] },

  { id: "the_thief_known", prio: 5,
    cond: (g) => S(g, "crime") >= 6 && rank(g) >= 1,
    title: "A Name in the Underworld",
    text: () => "Your thieving has not gone unnoticed. A fixer in the Neon Labyrinth sends word: there is a place for someone with your hands, if you want a name in the underworld rather than just a record.",
    choices: [
      { label: "Take the name. Build a career out of it.", fx: (g) => { sf(g, "street", 8); sf(g, "substrata", 4); flag(g, "underworldName"); return "You step into the underworld as a known quantity. The job board opens wider for you now."; } },
      { label: "Stay a ghost. Names get people killed.", fx: (g) => { Engine.coolHeat(g, 10); return "You stay nameless and careful. The heat on you cools, but the bigger jobs stay shut."; } },
    ] },

  { id: "made", prio: 7,
    cond: (g) => rank(g) >= 2 && (g.flags.crimeJobsDone || 0) >= 2 && !g.flags.made,
    title: "An Offer to Be Made",
    text: () => "A Matron of one of the Ironwall families wants to make you — to swear you in, blood and oath, as one of her own. It is the difference between an earner and a member: protection, a cut of everything, and a debt you can never fully repay.",
    choices: [
      { label: "Swear in. Become family.", fx: (g) => { flag(g, "made"); sf(g, "ironwall", 14); sf(g, "guild", -4); style(g, "crime", 2); return "You take the oath. You are made now — owned and protected in the same breath."; } },
      { label: "Stay independent. Owe no one.", fx: (g) => { sf(g, "street", 6); sf(g, "ironwall", -3); return "You stay your own operator. The street respects it; the family files it away."; } },
    ] },

  { id: "the_betrayal", prio: 8,
    cond: (g) => g.flags.made && rank(g) >= 3 && g.day >= 7,
    title: "Sold Out",
    text: () => "Someone in your own crew has sold your routes to a rival family. You know who. The whole underworld is watching to see what a made member does about a traitor.",
    choices: [
      { label: "Kill them. Make it a message.", fx: (g) => { style(g, "violence", 4); Engine.addHeat(g, 18); sf(g, "ironwall", 8); Engine.injure(g, "knife-fight cut", 1); return "You handle it the old way. The message lands; so does a blade. Your name is feared now, and hunted."; } },
      { label: "Buy their silence and their debt.", fx: (g) => { coin(g, -Math.min(g.money, 80)); sf(g, "street", 4); return "You buy the traitor whole — silence, debt, and leverage. Cheaper than blood, in the end."; } },
      { label: "Vanish to a region until it cools.", fx: (g) => { Engine.coolHeat(g, 20); style(g, "wander", 3); return "You leave the city to the families' war and ride out. The heat fades; so does your grip on the crew."; } },
    ] },

  { id: "the_boss_offer", prio: 9,
    cond: (g) => rank(g) >= 4,
    title: "The Job Every Earner Dreams Of",
    text: () => "You have risen as far as the underworld goes without a crown. The families put one offer on the table: the Spire vault job. Pull it and you are a boss; the city's locks open for you. Most who try it die above the smog.",
    choices: [
      { label: "Take the vault job. Reach for the crown.", fx: (g) => { flag(g, "bossTrack"); style(g, "crime", 3); return "You start assembling the crew for the impossible. (Take 'The Spire vault job' from the Underworld board when you're ready.)"; } },
      { label: "Walk away a legend, alive.", fx: (g) => { sf(g, "street", 10); sf(g, "substrata", 6); return "You turn down the crown and keep your life. In the underworld, that restraint becomes its own legend."; } },
    ] },

  { id: "hunted", prio: 10,
    cond: (g) => (g.heat || 0) >= 55,
    title: "Bounty Hunters",
    text: () => "Your notoriety has a price on it now, and someone has come to collect. Two hunters corner you where the streets are thin.",
    choices: [
      { label: "Fight your way clear.", fx: (g) => { const ck = Engine.check(g, "blade", 55); if (ck.ok) { Engine.addHeat(g, -10); return "You put both hunters down and walk out. The bounty stands, but you've bought time."; } Engine.injure(g, "bounty-hunter wound", 2); return "It goes badly. You escape, bleeding, with the price on your head only higher."; } },
      { label: "Pay them off with the bounty itself.", fx: (g) => { const pay = Math.min(g.money, (g.bounty || 30)); coin(g, -pay); Engine.coolHeat(g, 30); return `You buy the hunters off for ${pay} shekels and a promise. The heat on you cools sharply.`; } },
      { label: "Flee the City for a region.", fx: (g) => { Engine.coolHeat(g, 40); style(g, "wander", 2); return "You run for the open country and let the trail go cold. (Travel a region from the Caravanserai to be sure of it.)"; } },
    ] },

  { id: "devout", prio: 4,
    cond: (g) => S(g, "piety") >= 8 && Engine.factionRep(g, "temple") > 10,
    title: "A Charge from the Priesthood",
    text: () => "You have kept the rites faithfully, and the priesthood has marked you. A senior priest puts a charge to you — there is a matter in the deep records the temple needs handled by someone who believes.",
    choices: [
      { label: "Accept the charge.", fx: (g) => { sf(g, "temple", 10); flag(g, "templeCharge"); style(g, "piety", 2); return "You take the temple's charge. The Ziggurat Crown counts you among its trusted now."; } },
      { label: "Decline — faith is private.", fx: (g) => { sf(g, "temple", -3); return "You keep your faith your own. The priest nods, disappointed but not surprised."; } },
    ] },

  { id: "the_council_adopts", prio: 4,
    cond: (g) => S(g, "charity") >= 6 && (g.rep.broken_crown || 0) > 20,
    title: "One of Our Own",
    text: () => "You have done real work for the Broken Crown — not for points, but because it needed doing. The neighborhood council names you one of theirs, papers or no.",
    choices: [
      { label: "Accept. These are your people now.", fx: (g) => { rep(g, "broken_crown", 12); sf(g, "broken_crown", 10); flag(g, "councilKin"); return "The council takes you in. In a city that won't admit you exist, forty thousand people now will."; } },
      { label: "Thank them, but stay apart.", fx: (g) => { rep(g, "broken_crown", 3); return "You keep your distance, but the offer changes how the Crown sees you."; } },
    ] },

  { id: "silver_tongue", prio: 4,
    cond: (g) => S(g, "deception") >= 8 && g.day >= 3,
    title: "A Tongue for Hire",
    text: () => "Your way with a lie has reached the wrong — or right — ears. A guild broker offers to put your tongue to work in negotiations that need a certain creative honesty.",
    choices: [
      { label: "Take the work. Words are a weapon too.", fx: (g) => { sf(g, "guild", 8); coin(g, 50); style(g, "deception", 2); return "You sign on as the guild's deniable voice. Lucrative, and quietly compromising."; } },
      { label: "Refuse. Some lies cost too much.", fx: (g) => { sf(g, "guild", -2); return "You turn the broker down. The restraint is noted; the coin is not yours."; } },
    ] },

  { id: "merchant_prince", prio: 5,
    cond: (g) => S(g, "commerce") >= 10 && g.money >= 400,
    title: "A Seat at the Table",
    text: () => "You have built real coin and a name in the markets. A trade guild offers you a seat on its council — a share of the power that sets the city's prices.",
    choices: [
      { label: "Take the seat.", fx: (g) => { sf(g, "guild", 14); flag(g, "guildSeat"); coin(g, -100); return "You buy in. You help set the prices now — which means the bread riots, when they come, are partly yours."; } },
      { label: "Stay a free trader.", fx: (g) => { sf(g, "guild", 2); return "You keep your independence and your conscience, such as it is."; } },
    ] },

  /* ===== PROTAGONIST ARCS — react to the specific person AND how they play ===== */
  { id: "acolyte_accusation", prio: 6,
    cond: (g) => g.proto === "acolyte" && g.day >= 2,
    title: "The Altered Record",
    text: () => "The elders summon you over the prayer-record you did not alter. " + (S(g, "piety") >= 4 ? "Your evident devotion buys you a hearing rather than a sentence." : "Your thin attendance at the rites has not helped your case."),
    choices: [
      { label: "Argue your innocence with everything you have.", fx: (g) => { const ck = Engine.check(g, "rhetoric", 50); if (ck.ok) { flag(g, "acolyteCleared"); sf(g, "temple", 6); return "You hold your ground and the elders waver. You are not cleared — but you are not condemned, and now you can hunt the real forger."; } sf(g, "temple", -6); flag(g, "acolyteCondemned"); return "Your words fail. The temple marks you guilty in all but sentence; the Crown grows cold."; } },
      { label: "Confess falsely and beg mercy.", fx: (g) => { sf(g, "temple", -3); style(g, "deception", 2); flag(g, "acolyteConfessed"); return "You confess to a thing you did not do. Mercy is given, and a leash with it."; } },
    ] },
  { id: "acolyte_truth", prio: 7,
    cond: (g) => g.proto === "acolyte" && g.flags.acolyteCleared && g.day >= 4,
    title: "Who Forged the Record",
    text: () => "Your own quiet inquiry turns up the forger: Junior Priest Eshu, your superior, protecting a doctrinal lie of his own. You hold the proof.",
    choices: [
      { label: "Expose him to the elders.", fx: (g) => { sf(g, "temple", 8); rep(g, "ziggurat_crown", 10); return "You lay the proof before the elders. Eshu falls; the Crown's faction shudders, and your name is cleared in full."; } },
      { label: "Blackmail him — leverage is worth more than justice.", fx: (g) => { style(g, "crime", 2); style(g, "deception", 2); coin(g, 60); flag(g, "eshuLeash"); return "You keep the proof and put Eshu on a leash. Justice can wait; leverage compounds."; } },
    ] },

  { id: "merchant_rival", prio: 6,
    cond: (g) => g.proto === "merchant" && g.day >= 2,
    title: "Your Father's Problem",
    text: () => "Your father lays it plainly: the rival undercutting the family stall for three months has to be handled, and he is leaving how to you.",
    choices: [
      { label: "Beat them at the trade — cut deeper, win the floor.", fx: (g) => { style(g, "commerce", 3); sf(g, "guild", 5); coin(g, -40); return "You wage a price war and grind the rival down honestly. It costs you now and pays later."; } },
      { label: "Have their stock spoiled — quietly.", fx: (g) => { style(g, "crime", 3); Engine.addHeat(g, 8); sf(g, "ironwall", 3); return "You arrange an accident for their warehouse. The rival folds; a thread now ties you to the Ironwall."; } },
      { label: "Make peace and split the route.", fx: (g) => { style(g, "charity", 2); sf(g, "guild", 3); return "You offer the rival a partnership instead of a war. Your father thinks you soft; the Market thinks you wise."; } },
    ] },

  { id: "scion_debt", prio: 6,
    cond: (g) => g.proto === "scion" && g.day >= 1,
    title: "Collect from the Clinic",
    text: () => "Your family orders you to collect a debt from a Broken Crown clinic that cannot pay — the same clinic that once kept you alive.",
    choices: [
      { label: "Collect by force. Family is family.", fx: (g) => { style(g, "violence", 3); sf(g, "ironwall", 6); rep(g, "broken_crown", -12); coin(g, 50); return "You take the family's due from people who have nothing. The Ironwall approves; the Crown will not forget."; } },
      { label: "Forgive the debt and pay it yourself.", fx: (g) => { style(g, "charity", 3); coin(g, -Math.min(g.money, 60)); rep(g, "broken_crown", 12); sf(g, "ironwall", -5); return "You cover the clinic's debt from your own purse. The family is insulted; the Crown remembers a Kol who chose mercy."; } },
      { label: "Tell the family it's collected — and lie.", fx: (g) => { style(g, "deception", 3); flag(g, "scionLie"); rep(g, "broken_crown", 8); return "You report the debt collected and pocket nothing. The lie will hold — until it doesn't."; } },
    ] },

  { id: "runner_debt", prio: 6,
    cond: (g) => g.proto === "runner" && g.day >= 2,
    title: "The Fixer Calls the Debt",
    text: () => "The fixer who put the optics in your skull wants paying. The debt for your eyes has come due, and the interest is not in coin alone.",
    choices: [
      { label: "Pay it off in full.", fx: (g) => { coin(g, -Math.min(g.money, 90)); sf(g, "street", 5); return "You clear the debt and own your own eyes at last. The purse hurts; the freedom doesn't."; } },
      { label: "Work it off with a job.", fx: (g) => { style(g, "crime", 2); flag(g, "runnerJobOwed"); sf(g, "street", 3); return "You agree to run a job against the debt. (Take work from the Underworld board.) The leash stays on a while longer."; } },
      { label: "Steal the parts to clear yourself.", fx: (g) => { style(g, "crime", 3); Engine.addHeat(g, 12); return "You decide to take what you owe rather than pay it. The fixer will not take that quietly."; } },
    ] },

  { id: "slum_wall", prio: 7,
    cond: (g) => g.proto === "slumborn" && g.day >= 2,
    title: "The Wall and the Eight Thousand",
    text: () => "The corporation's demolition of your block is dated. Eight thousand people live behind that wall, and the law says the wall does not exist. They are looking at you to decide what happens next.",
    choices: [
      { label: "Organize the blockade. Stand the ground.", fx: (g) => { style(g, "charity", 4); rep(g, "broken_crown", 16); sf(g, "broken_crown", 10); sf(g, "corporate", -8); flag(g, "blockade"); return "You put yourself at the front of eight thousand. The Crown will follow you now; the corporation marks you an obstacle."; } },
      { label: "Take the corporation's quiet buyout.", fx: (g) => { coin(g, 200); rep(g, "broken_crown", -20); sf(g, "corporate", 6); flag(g, "soldOut"); return "You take their coin and let the wall fall. You are rich, and you can never go home to the Crown again."; } },
      { label: "Sabotage the demolition rig.", fx: (g) => { style(g, "crime", 3); style(g, "violence", 1); Engine.addHeat(g, 14); rep(g, "broken_crown", 8); sf(g, "corporate", -6); return "You wreck the rig in the dark. The demolition stalls; the corporation starts hunting whoever did it."; } },
    ] },

  { id: "law_ledger", prio: 6,
    cond: (g) => g.proto === "lawspeaker" && g.day >= 3,
    title: "The Trail of the Herd-Ledger",
    text: () => "Your inquiry into the stolen herd-ledger of your confederation ends, as you feared, in the Sub-Strata — held by a smuggler who knows exactly what it's worth.",
    choices: [
      { label: "Talk it back — the law-speaker's craft.", fx: (g) => { const ck = Engine.check(g, "rhetoric", 55); if (ck.ok) { sf(g, "steppe", 10); flag(g, "ledgerRecovered"); return "You argue the smuggler into a corner with the confederation's own law. The ledger is yours; the Steppe owes you."; } sf(g, "substrata", -3); return "Your words don't move the smuggler. The ledger stays lost, for now."; } },
      { label: "Take it by force.", fx: (g) => { const ck = Engine.check(g, "blade", 55); style(g, "violence", 3); Engine.addHeat(g, 8); if (ck.ok) { flag(g, "ledgerRecovered"); sf(g, "steppe", 6); return "You take the ledger at the point of a blade. The confederation has it back, and a debt of blood follows you."; } Engine.injure(g, "smuggler's blade", 2); return "The smuggler's people are ready for force. You come away hurt and empty-handed."; } },
      { label: "Buy it — pay the underworld's price.", fx: (g) => { coin(g, -Math.min(g.money, 120)); sf(g, "substrata", 4); flag(g, "ledgerRecovered"); return "You pay the smuggler's price. The ledger goes home; your purse does not."; } },
    ] },

  /* new protagonists — one strong arc beat each */
  { id: "highlander_charter", prio: 6,
    cond: (g) => g.proto === "highlander" && g.day >= 2,
    title: "The Forged Charter",
    text: () => "The broker who sold your clan's obsidian under a forged charter holds court in the Spire. You came to take it back or break the deal.",
    choices: [
      { label: "Break him by force.", fx: (g) => { style(g, "violence", 3); Engine.addHeat(g, 12); sf(g, "corporate", -6); return "You handle the broker the highland way. The deal breaks; so does the peace."; } },
      { label: "Contest the charter in religious court.", fx: (g) => { style(g, "loyalty", 1); sf(g, "temple", 5); flag(g, "charterContested"); return "You take the forgery to the only court older than the corporations. Slow, but it cannot be bought."; } },
    ] },
  { id: "fracture_breach", prio: 6,
    cond: (g) => g.proto === "fracturehack" && g.day >= 2,
    title: "They Have Your Name",
    text: () => "The corporation whose systems you once broke has finally put your name to the breach. They are looking for you in the Labyrinth.",
    choices: [
      { label: "Go to ground in the underworld.", fx: (g) => { sf(g, "street", 6); Engine.coolHeat(g, 6); style(g, "crime", 1); return "You disappear into the street's protection. Safer — and deeper in their debt."; } },
      { label: "Breach them again — bury the evidence.", fx: (g) => { const ck = Engine.check(g, "hacking", 58); if (ck.ok) { flag(g, "evidenceBuried"); return "You go back in and erase yourself from their records. Audacious, and it works."; } Engine.addHeat(g, 16); return "The breach trips an alarm. Now they don't just have your name — they have your face."; } },
    ] },
  { id: "dyula_route", prio: 6,
    cond: (g) => g.proto === "dyula" && g.day >= 2,
    title: "Six Generations of Road",
    text: () => "A corporate logistics firm is moving to cut your family out of a route the Dyula have held for six generations. You can fight it on their terms or yours.",
    choices: [
      { label: "Undersell them into the ground.", fx: (g) => { style(g, "commerce", 3); sf(g, "guild", 6); sf(g, "corporate", -4); return "You wage the trade war the Dyula were born for. The corporation underestimated whose road it is."; } },
      { label: "Pull the region trade out from under them.", fx: (g) => { style(g, "wander", 2); flag(g, "dyulaRoutes"); return "You ride the routes yourself and lock in the producing regions. (Region trade is now your weapon.)"; } },
    ] },
  { id: "holds_charter", prio: 6,
    cond: (g) => g.proto === "holdsnoble" && g.day >= 2,
    title: "The Mining Charter",
    text: () => "The charter your family contests as fraudulent is set to be ratified this week, here in the city.",
    choices: [
      { label: "Buy the votes you need.", fx: (g) => { coin(g, -Math.min(g.money, 150)); sf(g, "guild", 6); return "You spend your family's coin the way the corporations do. The ratification stalls."; } },
      { label: "Expose the fraud publicly.", fx: (g) => { const ck = Engine.check(g, "rhetoric", 52); if (ck.ok) { sf(g, "corporate", -8); flag(g, "charterExposed"); return "You lay the fraud bare before the council. The charter dies; the corporation makes an enemy of your house."; } return "Your evidence isn't enough yet. The charter moves forward."; } },
    ] },
  { id: "delta_message", prio: 6,
    cond: (g) => g.proto === "deltarunner" && g.day >= 2,
    title: "The Message You Carried",
    text: () => "The message you brought into the city is something a powerful person would kill to keep unread. Now you can't leave — and you still hold it.",
    choices: [
      { label: "Sell it to the highest bidder.", fx: (g) => { coin(g, 180); style(g, "crime", 2); Engine.addHeat(g, 12); return "You auction the secret. Rich and marked — the buyer and the subject both now know your face."; } },
      { label: "Deliver it as you swore you would.", fx: (g) => { style(g, "loyalty", 3); sf(g, "delta", 0); rep(g, "broken_crown", 6); flag(g, "messageDelivered"); return "You keep your word and deliver it true. The powerful are furious; the people you carried it for are not."; } },
    ] },

  /* ===== CHAINED CONSEQUENCES — the world answers what you've done ===== */
  { id: "corp_retaliation", prio: 8,
    cond: (g) => g.flags.blockade && g.day >= 5,
    title: "The Corporation Answers",
    text: () => "Your blockade held, so the corporation changes tactics. Private security moves on the Broken Crown at night; three city council members with corporate money are calling you a terrorist. Eight thousand people are looking at you again.",
    choices: [
      { label: "Hold the line and call in the Sub-Strata networks.", fx: (g) => { sf(g, "substrata", 8); sf(g, "broken_crown", 8); sf(g, "corporate", -10); Engine.addHeat(g, 10); flag(g, "wallSaved"); return "The Sub-Strata answers; the demolition becomes impossible to enforce. The wall stands — and you are now a name the corporations fear."; } },
      { label: "Cut a deal: the wall stays, you go quiet.", fx: (g) => { sf(g, "corporate", 4); rep(g, "broken_crown", 4); flag(g, "wallSaved"); return "You trade your silence for the wall's survival. The block is safe; your fire is spent."; } },
      { label: "Let it burn — escalate to open sabotage.", fx: (g) => { style(g, "violence", 3); style(g, "crime", 3); Engine.addHeat(g, 20); sf(g, "corporate", -14); return "You take the fight to the corporation's infrastructure. It becomes a war, and wars take everyone."; } },
    ] },

  { id: "family_war", prio: 8,
    cond: (g) => g.flags.made && (g.cascades.some((c) => c.id === "raid" || c.id === "war") || g.day >= 11),
    title: "The Families Go to War",
    text: () => "The low-temperature civil war between the Ironwall families has turned hot, and you are made — you do not get to sit this out. Your Matron asks where your blade falls.",
    choices: [
      { label: "Lead her crews. Win the streets.", fx: (g) => { style(g, "violence", 4); sf(g, "ironwall", 10); Engine.addHeat(g, 16); Engine.injure(g, "war wound", 1 + Engine.rand(2)); return "You lead from the front. Your family gains ground, paid for in blood including some of your own."; } },
      { label: "Broker a peace between the families.", fx: (g) => { const ck = Engine.check(g, "rhetoric", 60); if (ck.ok) { sf(g, "ironwall", 6); flag(g, "warBroker"); return "You do the impossible and talk the families down. Both owe you now; neither fully trusts you."; } sf(g, "ironwall", -6); return "Your peace fails and the war grinds on, with your name attached to the failure."; } },
    ] },

  { id: "guild_riot", prio: 8,
    cond: (g) => g.flags.guildSeat && g.cascades.some((c) => c.id === "drought"),
    title: "The Price of Bread",
    text: () => "The drought has driven grain to the ceiling, and you sit on the guild council that sets the price. The Broken Crown is starving; the council wants the price held high. The vote is yours to swing.",
    choices: [
      { label: "Hold the price. Profit is profit.", fx: (g) => { coin(g, 150); sf(g, "guild", 6); rep(g, "broken_crown", -16); sf(g, "broken_crown", -10); return "You vote with the council and the price holds. You are rich, and the bread riots that follow are partly your doing."; } },
      { label: "Break ranks and force the price down.", fx: (g) => { sf(g, "guild", -10); rep(g, "broken_crown", 16); sf(g, "broken_crown", 12); style(g, "charity", 3); return "You break the council to feed the slums. The guild will not forgive it; forty thousand people will not forget it."; } },
    ] },

  { id: "temple_conspiracy", prio: 9,
    cond: (g) => g.flags.templeCharge && g.fragments.length >= 2,
    title: "What the Charge Was Really For",
    text: () => "The temple's charge has led you, fragment by fragment, to the edge of the thing the priesthood does not say aloud: that the gods they serve are tenants, and something older sleeps under the deep walls. A senior priest asks if you will keep looking — or stop.",
    choices: [
      { label: "Keep digging. The truth is worth the cost.", fx: (g) => { flag(g, "seeker"); sf(g, "temple", 4); return "You take the deeper road. The priesthood is afraid of what you might find — and so, a little, are you."; } },
      { label: "Bury it. Some doors should stay shut.", fx: (g) => { sf(g, "temple", 8); flag(g, "doorShut"); return "You let the matter lie and the priesthood breathes easier. The mystery waits, as it has for four thousand years."; } },
    ] },

  /* ===== CLIMAXES — each protagonist's arc resolves, shaped by your history ===== */
  { id: "acolyte_climax", prio: 12,
    cond: (g) => g.proto === "acolyte" && g.day >= 10,
    title: "What Became of the Acolyte",
    text: (g) => g.flags.seeker ? "You came to the temple accused of altering one record, and you leave it carrying the heaviest truth in the world."
      : g.flags.eshuLeash ? "You were framed, and instead of clearing your name you took the man who framed you and made him yours."
      : (Engine.factionRep(g, "temple") > 25) ? "The accusation that opened your story is long buried. The Crown counts you among the faithful who matter now."
      : "The temple never quite trusted you again. You found your faith elsewhere, or lost it.",
    choices: [
      { label: "Accept what you've become.", fx: (g) => { flag(g, "arcDone"); const d = dom(g); return d === "piety" ? "You end as the priesthood's quiet conscience — devout, and dangerous to liars." : d === "crime" ? "You end with a priest's robes and a thief's hands, which is its own kind of power." : "You end having learned that survival inside a holy place is its own long prayer."; } },
    ] },
  { id: "scion_climax", prio: 12,
    cond: (g) => g.proto === "scion" && g.day >= 10,
    title: "What Became of the Scion",
    text: (g) => g.rep.broken_crown > 10 ? "You were born a warlord's child and chose, more than once, the people your family preys on. Both worlds claim you now; neither owns you."
      : (Engine.factionRep(g, "ironwall") > 30) ? "You became exactly what the Kol blood intended — and the family is stronger for it, and crueller."
      : "You drifted from the family without ever fully breaking — a Kol in name, something else in fact.",
    choices: [
      { label: "Choose your house.", fx: (g) => { flag(g, "arcDone"); return dom(g) === "charity" ? "You end as the Kol who broke the pattern — protected by the family, trusted by the slums." : dom(g) === "violence" ? "You end as the family's sharpest blade, feared on every street they hold." : "You end having learned that blood is a door, not a cage."; } },
    ] },
  { id: "slum_climax", prio: 12,
    cond: (g) => g.proto === "slumborn" && g.day >= 9 && (g.flags.wallSaved || g.flags.soldOut || g.flags.blockade),
    title: "What Became of the Slum-Born",
    text: (g) => g.flags.wallSaved ? "The wall that does not legally exist still stands, and eight thousand people behind it know whose nerve held it up."
      : g.flags.soldOut ? "The wall fell and you grew rich, and you can never walk the Broken Crown again as one of its own."
      : "You stood in front of the demolition and what came of it is now part of the Crown's long memory of itself.",
    choices: [
      { label: "Take the measure of it.", fx: (g) => { flag(g, "arcDone"); return g.flags.soldOut ? "You end with money and no home — the oldest bargain in the city." : "You end as proof that the undocumented can move the city that pretends they don't exist."; } },
    ] },
  { id: "crime_boss_climax", prio: 13,
    cond: (g) => rank(g) >= 5,
    title: "Boss of the Underworld",
    text: () => "You started lifting purses in the market crowds. You end holding the underworld of the largest city in the world — the families answer to you, the Sub-Strata moves for you, and three of the people who govern the city privately regard you as a peer.",
    choices: [
      { label: "Rule from the shadows.", fx: (g) => { flag(g, "arcDone"); sf(g, "ironwall", 6); sf(g, "street", 6); return "You take the crown no one can see. The City is yours in all the ways that the law will never record."; } },
      { label: "Cash out and disappear a legend.", fx: (g) => { flag(g, "arcDone"); coin(g, 300); Engine.coolHeat(g, 50); return "You walk away at the top — the rarest ending in the underworld, and the only happy one."; } },
    ] },
  { id: "capstone", prio: 11,
    cond: (g) => g.day >= 13 && !g.flags.arcDone,
    title: "The Weight of What You've Done",
    text: (g) => { const d = dom(g); const m = { violence: "blood", crime: "stolen coin and broken locks", piety: "kept rites and quiet faith", charity: "debts paid that were never yours", deception: "useful lies", commerce: "ledgers and leverage", wander: "roads walked to the edge of the world", loyalty: "promises kept past sense" }; return `A specific history is yours now — built not from destiny but from ${m[d] || "the choices you actually made"}. No other player has it. The City does not thank you; it simply continues, carrying the mark you left.`; },
    choices: [
      { label: "Carry it forward.", fx: (g) => { flag(g, "arcDone"); return "You understand something true now about power, time, and what it costs to be a person inside history. That was always the point."; } },
    ] },
];

/* --------------------------------------------------------------------------
 * Engine hooks
 * -------------------------------------------------------------------------- */
Story.check = function (g) {
  if (!g || g.over || Story._active) return;
  if (!g.story) g.story = { seen: [], stage: 0 };
  const eligible = Story.BEATS.filter((b) => !g.story.seen.includes(b.id) && b.cond(g));
  if (!eligible.length) return;
  eligible.sort((a, b) => (b.prio || 0) - (a.prio || 0));
  Story.fire(eligible[0], g);
};
Story.onNewDay = function (g) { Story.check(g); };

Story.fire = function (beat, g) {
  g.story.seen.push(beat.id);
  Story._active = beat;
  if (document.pointerLockElement) document.exitPointerLock();
  let html = `<h2>${beat.title || "A Turn in Your Story"}</h2><p style="font-size:14px;line-height:1.6">${beat.text(g)}</p><div style="display:flex;flex-direction:column;gap:8px;margin-top:14px">`;
  beat.choices.forEach((c, i) => { html += `<button class="primary" style="text-align:left" onclick="window.Story.choose(${i})">${c.label}</button>`; });
  html += `</div><p class="muted small" style="margin-top:10px">There is no clean choice. Every path here costs something.</p>`;
  if (window.UI && UI.modal) UI.modal(html);
};

Story.choose = function (i) {
  const g = State.data, beat = Story._active; if (!beat) return;
  const c = beat.choices[i]; if (!c) return;
  const line = c.fx(g) || "";
  if (!g.story.log) g.story.log = [];
  g.story.log.push({ day: g.day, title: beat.title, choice: c.label, line });
  Engine.push(g, `❖ ${beat.title}: ${line}`, "reveal");
  Story._active = null;
  if (window.UI && UI.closeModal) UI.closeModal();
  if (window.World3D && World3D.updateHUD) World3D.updateHUD();
  if (window.State) State.save();
};
